# Cloudflare Pages configuration
name = "labjp-blog"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "blog-analytics"
database_id = "0f5e7fb3-24dd-4498-a6a4-9b27e3264748"
